version: '2'
services:
  openldap:
    image: osixia/openldap:1.2.2
    network_mode: bridge
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
    ports:
      - "389:389"
      - "636:636
